---
web:
  # The host that the management interface will be available on
  host: <%= ENV["POSTAL_WEB_HOST"] %>
  # The protocol that requests to the management interface should happen on
  protocol: <%= ENV["POSTAL_WEB_PROTOCOL"] %>

web_server:
  bind_address: <%= ENV["POSTAL_WEB_SERVER_BIND_ADDRESS"] %>
  port: <%= ENV["POSTAL_WEB_SERVER_PORT"] %>
  max_threads: <%= ENV["POSTAL_WEB_SERVER_MAX_THREADS"] %>

fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: <%= ENV["POSTAL_FAST_SERVER_ENABLED"] %>
  bind_address: <%= ENV["POSTAL_FAST_SERVER_BIND_ADDRESS"] %>
  port: <%= ENV["POSTAL_FAST_SERVER_PORT"] %>
  ssl_port: <%= ENV["POSTAL_FAST_SERVER_SSL_PORT"] %>

general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: false
  exception_url: <%= ENV["POSTAL_GENERAL_EXCEPTION_URL"] %>
  # Always use local DNS resolver, rather than attempting to find a nameserver
  # by stepping through domain parts, which seems to give us a result of
  # `0.0.0.0`, which obviously doesn't work if you try to use it for
  # resolution.
  use_local_ns_for_domains: true
  # Disable Postal's self-management of SSL for tracking domains
  use_external_ssl_for_tracking: <%= ENV["POSTAL_GENERAL_USE_EXTERNAL_SSL_FOR_TRACKING"] %>

main_db:
  # Specify the connection details for your MySQL database
  host: <%= ENV["MYSQL_HOST"] %>
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  database: <%= ENV["MYSQL_DATABASE_MAIN"] %>

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: <%= ENV["MYSQL_HOST"] %>
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  prefix: <%= ENV["MYSQL_DATABASE_MESSAGE_PREFIX"] %>

rabbitmq:
  # Specify the connection details for your RabbitMQ server.
  host: <%= ENV["RABBITMQ_HOST"] %>
  username: <%= ENV["RABBITMQ_USER"] %>
  password: <%= ENV["RABBITMQ_PASSWORD"] %>
  vhost: <%= ENV.fetch("RABBITMQ_VHOST", "/postal") %>

dns:
  # Specifies the DNS record that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - <%= ENV["POSTAL_DNS_MX_RECORD"] %> # mx.postal.example.com
  smtp_server_hostname: <%= ENV["POSTAL_DNS_SMTP_SERVER_HOSTNAME"] %> # postal.example.com
  spf_include: <%= ENV["POSTAL_DNS_SPF_INCLUDE"] %> # spf.postal.example.com
  return_path: <%= ENV["POSTAL_DNS_RETURN_PATH"] %> # rp.postal.example.com
  route_domain: <%= ENV["POSTAL_DNS_ROUTE_DOMAIN"] %> # routes.postal.example.com
  track_domain: <%= ENV["POSTAL_DNS_TRACK_DOMAIN"] %> # track.postal.example.com

smtp_server:
  port: <%= ENV["POSTAL_SMTP_SERVER_PORT"] %>

<% if ENV["POSTAL_SMTP_RELAY_HOSTNAME"] %>
smtp_relays:
  - hostname: <%= ENV["POSTAL_SMTP_RELAY_HOSTNAME"] %>
    port: <%= ENV["POSTAL_SMTP_RELAY_PORT"] %>
    ssl_mode: <%= ENV["POSTAL_SMTP_RELAY_SSL_MODE"] %>
    user: <%= ENV["POSTAL_SMTP_RELAY_USER"] %>
    secret: <%= ENV["POSTAL_SMTP_RELAY_SECRET"] %>
<% end %>

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: <%= ENV["POSTAL_SMTP_HOST"] %> # 127.0.0.1
  port: <%= ENV["POSTAL_SMTP_PORT"] %> # 2525
  username: <%= ENV["POSTAL_SMTP_USERNAME"] %> # Complete when Postal is running and you can
  password: <%= ENV["POSTAL_SMTP_PASSWORD"] %> # generate the credentials within the interface.
  from_name: <%= ENV["POSTAL_SMTP_FROM_NAME"] %> # Postal
  from_address: <%= ENV["POSTAL_SMTP_FROM_ADDRESS"] %> # postal@yourdomain.com

rails:
  environment: <%= ENV["RAILS_ENV"] %>
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: <%= ENV["POSTAL_RAILS_SECRET_KEY"] %>
